lapply(list.files("./R/", full.names = T), source)
data("staff", package = "workplanr")
data("projects", package = "workplanr")
data("project_phases", package = "workplanr")
data("project_roles", package = "workplanr")
data("out_of_office", package = "workplanr")
data("public_holidays", package = "workplanr")
data("time_estimates", package = "workplanr")
data("roles_responsibilities", package = "workplanr")
db_name = "my_workplan.sqlite"
create_new_workplan_db(staff = staff,
                       projects = projects,
                       project_phases = project_phases,
                       project_roles = project_roles,
                       out_of_office = out_of_office,
                       public_holidays = public_holidays,
                       time_estimates = time_estimates,
                       roles_responsibilities = roles_responsibilities,
                       staff_name_for_unassigned_work = "unassigned",
                       db_name = db_name)
data("project_assignments", package = "workplanr")
assign_staff(db_name = db_name, 
             staff_name = project_assignments$staff_name,
             project_name = project_assignments$project_name,
             project_role_name = project_assignments$project_role_name,
             staff_contribution = project_assignments$staff_contribution)
schedule = workplanr::get_schedule(db_name)
